robot_cfg:
  kinematics:
    usd_path: "robot/dcp_description/usd/fr5/fr5.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    external_asset_path: "/home/home/sdl_cutamp/src/sdl/content/assets"
    urdf_path: 'robot/dcp_description/urdf/robot/fr5.urdf'
    external_robot_configs_path: "/home/home/sdl_cutamp/src/sdl/content/configs/robot"
        
    base_link: "base_link"
    ee_link: "grasp_frame"
    link_names: null
    lock_joints: null
    extra_links: {
      "attached_object": {
        "parent_link_name": "grasp_frame",
        "link_name": "attached_object",
        "fixed_transform": [0,0,0,1,0,0,0],
        "joint_type":"FIXED",
        "joint_name": "attach_joint"
      }
    }

    collision_link_names: [
      'shoulder_link', 'upperarm_link', 'forearm_link', 'wrist1_link', 'wrist2_link', 'wrist3_link',
      "attached_object",
    ] # List[str]
    collision_spheres: "spheres/fr5.yml"

          
    collision_sphere_buffer: 0.005 # float or Dict[str, float]
    extra_collision_spheres: {"attached_object": 4}
    self_collision_ignore: {
      "shoulder_link": ["wrist3_link"],
      "upperarm_link": ["forearm_link", "shoulder_link", "wrist3_link"],
      "forearm_link": ["wrist1_link", "wrist2_link", "wrist3_link"],
      "wrist1_link": ["wrist2_link", "wrist3_link", "attached_object"],
      "wrist2_link": ["wrist3_link", "attached_object"],
    } # Dict[str, List[str]]
    self_collision_buffer: {
      'upperarm_link': 0,
      'forearm_link': 0, 
      'wrist1_link': 0, 
      'wrist2_link': 0,
      'wrist3_link': 0.025,
      'attached_object': 0.0,
    }  # Dict[str, float]

    use_global_cumul: True
    mesh_link_names: [
      'shoulder_link', 'upperarm_link', 'forearm_link', 'wrist1_link', 'wrist2_link' ,'wrist3_link'
    ] # List[str]

    cspace:
      joint_names: ['j1', 'j2', 'j3', 'j4', 'j5', 'j6'] # List[str]
      retract_config:  [0.0, -2.2, 1.9, -1.383, -1.57, 0.00]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1