# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
default_q: [
    0.0,0.0016,0.0005,0.0,-0.0,0.0
]

acceleration_limits: [
   10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - shoulder_link:
    - "center": [-0.0, -0.004, 0.159]
      "radius": 0.08675
  - upperarm_link:
    - "center": [0.001, -0.0, 0.14]
      "radius": 0.08774
    - "center": [-0.423, -0.003, 0.147]
      "radius": 0.08495
    - "center": [-0.22, -0.0, 0.138]
      "radius": 0.05883
    - "center": [-0.156, 0.0, 0.138]
      "radius": 0.05883
    - "center": [-0.283, -0.0, 0.138]
      "radius": 0.05883
    - "center": [-0.073, 0.002, 0.136]
      "radius": 0.07051
    - "center": [-0.354, 0.0, 0.136]
      "radius": 0.06161
  - forearm_link:
    - "center": [-0.009, 0.002, 0.035]
      "radius": 0.07595
    - "center": [-0.392, 0.0, 0.004]
      "radius": 0.06989
    - "center": [-0.249, 0.0, 0.0]
      "radius": 0.05439
    - "center": [-0.121, -0.0, -0.0]
      "radius": 0.05439
    - "center": [-0.059, 0.001, 0.0]
      "radius": 0.05338
    - "center": [-0.313, 0.001, -0.0]
      "radius": 0.05388
    - "center": [-0.184, -0.0, 0.0]
      "radius": 0.05439
  - wrist1_link:
    - "center": [-0.0, 0.004, 0.101]
      "radius": 0.06448
  - wrist2_link:
    - "center": [-0.0, -0.005, 0.097]
      "radius": 0.06448
  - wrist3_link:
    - "center": [-0.0, -0.0, 0.07]
      "radius": 0.05288
