##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot: 'fairino5_v6_robot'
urdf_path: "robot/dcp_description/urdf/robot/fr5.urdf"
collision_spheres: 
      shoulder_link:
        - "center": [-0.0, -0.004, 0.159]
          "radius": 0.08675
      upperarm_link:
        - "center": [0.001, -0.0, 0.14]
          "radius": 0.08774
        - "center": [-0.423, -0.003, 0.147]
          "radius": 0.08495
        - "center": [-0.22, -0.0, 0.138]
          "radius": 0.05883
        - "center": [-0.156, 0.0, 0.138]
          "radius": 0.05883
        - "center": [-0.283, -0.0, 0.138]
          "radius": 0.05883
        - "center": [-0.073, 0.002, 0.136]
          "radius": 0.07051
        - "center": [-0.354, 0.0, 0.136]
          "radius": 0.06161
      forearm_link:
        - "center": [-0.009, 0.002, 0.035]
          "radius": 0.07595
        - "center": [-0.392, 0.0, 0.004]
          "radius": 0.06989
        - "center": [-0.249, 0.0, 0.0]
          "radius": 0.05439
        - "center": [-0.121, -0.0, -0.0]
          "radius": 0.05439
        - "center": [-0.059, 0.001, 0.0]
          "radius": 0.05338
        - "center": [-0.313, 0.001, -0.0]
          "radius": 0.05388
        - "center": [-0.184, -0.0, 0.0]
          "radius": 0.05439
      wrist1_link:
        - "center": [-0.0, 0.004, 0.101]
          "radius": 0.06448
      wrist2_link:
        - "center": [-0.0, -0.005, 0.097]
          "radius": 0.06448
      wrist3_link:
        - "center": [-0.0, -0.0, 0.07]
          "radius": 0.05288